# Generated by Django 5.0.2 on 2024-02-25 10:16

import django.db.models.deletion
import phonenumber_field.modelfields
from apps import users
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('child', 'Child')], default='personal', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('two_factor', models.BooleanField(default=False)),
                ('recovery_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, validators=[
                    users.validators.auth.validate_name])),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, validators=[
                    users.validators.auth.validate_name])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not specified')], default='N', max_length=20)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tk', 'Turkmen')], default='tk', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('fingerprint', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('email_changed', 'Email changed'), ('phone_number_changed', 'Phone number changed'), ('password_changed', 'Password changed'), ('birthday', 'Birthday changed'), ('first_name_changed', 'First name changed'), ('last_name_changed', 'Last name changed'), ('avatar', 'Avatar changed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.device')),
            ],
        ),
    ]
